### PR TITLE
change name to displayName in Assignee and Reporter according to the …

### PR DESCRIPTION
**Pull request by ev2h**
…API response

name doesn't exist on Assignee or Reporter. I think they should be displayNames.

### CODE REVIEW

**Review by PhonyLou — CHANGES_REQUESTED** [review]
New files under the env folder look no use.

**Comment by zhangyuan** [comment]
Any update to this issue? I assume the reporters and assignees are all null based on the current master.

**Comment by zhangyuan** [comment]
> New files under the env folder look no use.

They are configuration examples. (this comment should go to another PR?)

**Comment by PhonyLou** [comment]
Just like file **dsafdf**, but no worry I will deal with it.

**Comment by zhangyuan** [comment]
I see. Didn't notice that.....Thanks!

**Pull request merged**
